### ISSUE TITLE
Experiment with windows host

### ISSUE THREAD

**Issue by Ash258** [Ash258/Scoop-GithubActions#55]
Installation of manifests could be easily done. Only question about performance, build time is on deck.

**Comment by Ash258** [comment]
Investigate if something like this will work:

```yml
name: Bucket Minion
description: Set of actions to automate maintaining of bucket.
author: Jakub <Ash258> Čábera
runs:
    using: pwsh
    main: Entrypoint.ps1
branding:
    icon: package
    color: purple
```
