### ISSUE TITLE
Excavator with automatic error reporting

### ISSUE THREAD

**Issue by Ash258** [Ash258/Scoop-GithubActions#62]
Auto-pr output could be hooked and then commet posted to specific issue defined as environment

```yml
      env:
        GITH_EMAIL: youremail@mail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
        OUTSTANDING_EXCAVATOR_ISSUE_ID: 258
```

This will require really high quality duplicate finder manager.
Teoretically it could be based on editing of Issue description, which will be list.
Markdown list will be parsed and based on check it will be `$true` or `$false`
If there is problem with updating and in list $false, nothing will happen.
If there is problem and list is $true, check description (name of application, version, type of error) and add to list.
Dump list to markdown.

Proper/best possible flow and implementation needs to be investigated
